version: "3"
services:
  app:
    cpus: 2
    mem_limit: 4g
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - PY_VER=${PY_VER:-3.11}
        - DISTRO=${DISTRO:-buster}
    image: datajoint/datajoint_tutorials:${PY_VER:-3.11}-${DISTRO:-buster}
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    volumes:
      - ..:/workspaces/datajoint-tutorials:cached
      - docker_data:/var/lib/docker  # persist docker images
    privileged: true # only because of dind
volumes:
  docker_data: